02-02-2024 16:59:00:[INFO]:__main__:train:133 - Init Encoder model... - [0:00:00.048149]
02-02-2024 16:59:01:[INFO]:__main__:train:149 - Init Predictor model... - [0:00:01.333235]
02-02-2024 16:59:01:[INFO]:__main__:train:167 - Init MultiBlockMaskCollator module... - [0:00:01.473467]
02-02-2024 16:59:01:[INFO]:__main__:train:193 - Init local dataset loading module... - [0:00:01.474518]
02-02-2024 16:59:01:[ERROR]:utils:load_checkpoint:170 - Error loading the model! [Errno 2] No such file or directory: './artifacts/i-jepa-latest.pth.tar' - [0:00:01.519061]
02-02-2024 16:59:01:[INFO]:__main__:train:244 - Training has started for epoch 0 - [0:00:01.519588]
02-02-2024 16:59:24:[INFO]:__main__:train:133 - Init Encoder model... - [0:00:00.047933]
02-02-2024 16:59:25:[INFO]:__main__:train:149 - Init Predictor model... - [0:00:01.342460]
02-02-2024 16:59:25:[INFO]:__main__:train:167 - Init MultiBlockMaskCollator module... - [0:00:01.483174]
02-02-2024 16:59:25:[INFO]:__main__:train:193 - Init local dataset loading module... - [0:00:01.484264]
02-02-2024 16:59:25:[ERROR]:utils:load_checkpoint:170 - Error loading the model! [Errno 2] No such file or directory: './artifacts/i-jepa-latest.pth.tar' - [0:00:01.530693]
02-02-2024 16:59:25:[INFO]:__main__:train:244 - Training has started for epoch 0 - [0:00:01.531270]
02-02-2024 17:06:26:[INFO]:__main__:train:296 - The loss at epoch 0 is 118.46137639434619 - [0:07:02.006490]
02-02-2024 17:06:26:[ERROR]:utils:save_checkpoint:130 - Model checkpoint save for epoch 0 has failed! Parent directory ./artifacts does not exist. - [0:07:02.032151]
02-02-2024 17:06:26:[INFO]:__main__:train:244 - Training has started for epoch 1 - [0:07:02.032506]
